import React from 'react';
import { X, TrendingUp, Globe, Users, Trophy, Target, Activity, Zap } from 'lucide-react';

interface CaseStudyModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
}

interface CaseStudyData {
  title: string;
  highlightColor: string;
  description: React.ReactNode;
  services: string[];
  chart?: {
    yLabel: string;
    yValues: (string | number)[];
    athLabel: string;
    pathFill: string;
    pathLine: string;
    gradientColor: string;
    lineColor: string;
    peakConfig: {
      cx: string;
      cy: string;
      r?: string;
    }
  };
  stats: {
    icon: React.ReactNode;
    value: string;
    label: string;
    sub: string;
  }[];
}

const CASE_STUDIES: Record<string, CaseStudyData> = {
  'TAOCAT': {
    title: '$TAOCAT',
    highlightColor: 'text-dynasty-lime',
    description: (
      <>
        <strong className="text-white">TAO Cat</strong> is Bittensor's first self-improving AI Agent — engineered by the Masa team and powered by Bittensor and Virtuals. She's not just a memecoin — she's an evolving, real-time AI built on decentralized infrastructure with a competitive spirit.
      </>
    ),
    services: [
      "Strategic Narrative & Go-to-Market Advisory",
      "KOL Marketing Strategy, Procurement & Execution",
      "Regional Growth Support (North America, South America, Europe, China)",
      "Exchange Outreach & Listing Campaign Support",
      "Post-launch Community and Ecosystem Liaison",
      "Community Management / Raiders"
    ],
    chart: {
      yLabel: "MARKET CAP",
      yValues: [100, 80, 60, 40, 20, 0],
      athLabel: "ATH: $80M",
      pathFill: "M0,200 L100,130 L200,110 L300,30 L300,200 L0,200 Z",
      pathLine: "M0,200 L100,130 L200,110 L300,30",
      gradientColor: "#F59E0B",
      lineColor: "#F59E0B",
      peakConfig: { cx: "300", cy: "30" }
    },
    stats: [
      {
        icon: <Users className="w-8 h-8 text-white" />,
        value: "80+",
        label: "KOLs & Communities",
        sub: "Go To Market Strategy"
      },
      {
        icon: <Globe className="w-8 h-8 text-white" />,
        value: "15+",
        label: "Exchange Listings",
        sub: "Kucoin, Binance Alpha, Mexc"
      },
      {
        icon: <Trophy className="w-8 h-8 text-white" />,
        value: "2x ROI",
        label: "Performance",
        sub: "REDACTED"
      }
    ]
  },
  'LAB TRADING': {
    title: 'LAB TRADING',
    highlightColor: 'text-dynasty-blue',
    description: (
      <>
        Multi-chain trading infrastructure – overlay, app & Telegram. Trade and analyze with sub-second execution, low fees, and transparent rewards 🧪
        <br /><br />
        Engaged alongside backers such as <strong className="text-white">Animoca Brands, Gate Ventures, OKX Ventures</strong>, and other venture firms. 
        <br /><br />
        All Time High Market Cap: <strong className="text-dynasty-lime">$750 Million FDV</strong>
        <br /><br />
        <span className="text-gray-400">Key Milestone:</span> Secured listings on major tier 1 & 2 exchanges on TGE including <strong className="text-white">Binance Alpha, Bitget, Bybit, OKX, etc.</strong>
      </>
    ),
    services: [
      "Critical product beta testing and feedback for UI / UX",
      "Instrumental to bringing key opinion leaders onboard to speak about the tool and bring early traders in to maximize airdrop speculation"
    ],
    stats: [
      {
        icon: <Activity className="w-8 h-8 text-white" />,
        value: "100M+",
        label: "Trading Volume",
        sub: "Before TGE"
      },
      {
        icon: <Zap className="w-8 h-8 text-white" />,
        value: "$750M",
        label: "ATH FDV",
        sub: "Fully Diluted Valuation"
      },
      {
        icon: <Users className="w-8 h-8 text-white" />,
        value: "18+",
        label: "Backers",
        sub: "Animoca Brands, OKX Ventures, GSR & more"
      }
    ]
  },
  'KINGMAKER': {
    title: 'KINGMAKER',
    highlightColor: 'text-dynasty-lime',
    description: (
      <>
        <strong className="text-white">Kingmaker</strong> is an AI trading tool. Trade with Confidence: Security, Speed, and Reliability You Can Trust. A Telegram-based platform enabling trades of any token on DEX at optimal prices. You can Buy and Sell tokens with their bot on SOL.
        <br /><br />
        Incubation from UI, UX, Go to Market Strategy, first 8000 users generated by Dynasty. Over 7 figures in trading volume.
        <br /><br />
        <span className="text-xs text-gray-500 italic">(Many numbers are redacted and confidential)</span>
        <br /><br />
        <div className="flex flex-wrap gap-4 mt-2">
            <a href="https://www.kingmaker.bot/" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-dynasty-lime hover:text-white transition-colors text-sm font-bold uppercase border border-dynasty-lime/20 px-4 py-2 rounded bg-dynasty-lime/5 hover:bg-dynasty-lime/10">
                <Globe className="w-4 h-4" /> Website
            </a>
            <a href="https://x.com/kingmakeralpha" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-dynasty-lime hover:text-white transition-colors text-sm font-bold uppercase border border-dynasty-lime/20 px-4 py-2 rounded bg-dynasty-lime/5 hover:bg-dynasty-lime/10">
                <svg viewBox="0 0 24 24" className="w-4 h-4" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
                Twitter / X
            </a>
        </div>
      </>
    ),
    services: [
        "Incubation (Zero to One)",
        "UI / UX Design Strategy",
        "Go To Market Strategy",
        "User Acquisition",
        "Human Resources",
        "Capital"
    ],
    stats: [
        {
          icon: <Users className="w-8 h-8 text-white" />,
          value: "8,000+",
          label: "Users Generated",
          sub: "First Cohort"
        },
        {
          icon: <Activity className="w-8 h-8 text-white" />,
          value: "$Xm+",
          label: "Trading Volume",
          sub: "Post-Launch"
        },
         {
          icon: <Target className="w-8 h-8 text-white" />,
          value: "REDACTED",
          label: "Confidential",
          sub: "Internal Metrics"
        }
    ]
  },
  'FLAP': {
    title: 'FLAP',
    highlightColor: 'text-purple-500',
    description: (
      <>
        <strong className="text-white">Flap</strong> is the OG launchpad of BNB memes and has since then evolved to serve emerging markets many other launchpads do not support such as <strong className="text-white">Monad</strong> & <strong className="text-white">X Layer</strong>.
        <br /><br />
        <div className="flex flex-wrap gap-4 mt-2">
            <a href="https://beta.flap.sh/bnb/board" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-purple-500 hover:text-white transition-colors text-sm font-bold uppercase border border-purple-500/20 px-4 py-2 rounded bg-purple-500/5 hover:bg-purple-500/10">
                <Globe className="w-4 h-4" /> Website
            </a>
            <a href="https://x.com/flapdotsh" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-purple-500 hover:text-white transition-colors text-sm font-bold uppercase border border-purple-500/20 px-4 py-2 rounded bg-purple-500/5 hover:bg-purple-500/10">
                <svg viewBox="0 0 24 24" className="w-4 h-4" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
                Twitter / X
            </a>
        </div>
      </>
    ),
    services: [
      "Introductions to launch teams / founders to launch within flap ecosystem",
      "Go To Market incubation support for projects launched on Flap",
      "Market Validation & Research"
    ],
    stats: [
        {
          icon: <Globe className="w-8 h-8 text-white" />,
          value: "3+",
          label: "Chains",
          sub: "BNB, Monad, X Layer"
        },
        {
          icon: <Zap className="w-8 h-8 text-white" />,
          value: "Instant",
          label: "Deployment",
          sub: "Meme Launchpad"
        },
         {
          icon: <Users className="w-8 h-8 text-white" />,
          value: "GTM",
          label: "Support",
          sub: "Founder Introductions"
        }
    ]
  },
  'OKX WALLET': {
    title: 'OKX WALLET',
    highlightColor: 'text-white',
    description: (
      <>
        <strong className="text-white">OKX Wallet</strong> is a next generation dex aggregator trading platform with the fastest order fills in the game. The crypto wallet for everything onchain. Self-custody is the future.
        <br /><br />
        <div className="flex flex-wrap gap-4 mt-2">
            <a href="https://web3.okx.com/join/DYNASTY" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-white hover:text-dynasty-lime transition-colors text-sm font-bold uppercase border border-white/20 px-4 py-2 rounded bg-white/5 hover:bg-white/10">
                <Globe className="w-4 h-4" /> Website
            </a>
            <a href="https://x.com/wallet" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-white hover:text-dynasty-lime transition-colors text-sm font-bold uppercase border border-white/20 px-4 py-2 rounded bg-white/5 hover:bg-white/10">
                <svg viewBox="0 0 24 24" className="w-4 h-4" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>
                Twitter / X
            </a>
        </div>
      </>
    ),
    services: [
      "UI / UX Feedback",
      "New Features Research",
      "User Acquisition",
      "Trading Volume Growth",
      "KOL Social Media Support"
    ],
    stats: [
        {
          icon: <Users className="w-8 h-8 text-white" />,
          value: "Growth",
          label: "User Acquisition",
          sub: "Strategic Campaigns"
        },
        {
          icon: <Activity className="w-8 h-8 text-white" />,
          value: "Volume",
          label: "Trading Growth",
          sub: "DEX Aggregation"
        },
         {
          icon: <Zap className="w-8 h-8 text-white" />,
          value: "Fastest",
          label: "Order Fills",
          sub: "Optimized Routing"
        }
    ]
  }
};

const CaseStudyModal: React.FC<CaseStudyModalProps> = ({ isOpen, onClose, projectId }) => {
  if (!isOpen) return null;

  const data = CASE_STUDIES[projectId];

  if (!data) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/95 backdrop-blur-md transition-opacity" 
        onClick={onClose}
      />
      
      {/* Modal Content */}
      <div className="relative w-full max-w-5xl bg-gradient-to-br from-[#0a1025] to-[#050505] border border-dynasty-blue/30 rounded-2xl overflow-hidden shadow-[0_0_50px_rgba(46,92,255,0.15)] animate-[fadeIn_0.3s_ease-out] flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-white/10 bg-white/5 shrink-0">
          <h2 className="text-2xl md:text-3xl font-display font-bold text-white tracking-wide">
            CASE STUDY: <span className={data.highlightColor}>{data.title}</span>
          </h2>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Scrollable Body */}
        <div className="overflow-y-auto custom-scrollbar p-6 md:p-10">
          
          {/* Top Section: Text + Chart (Conditional) */}
          <div className={`grid grid-cols-1 ${data.chart ? 'lg:grid-cols-2' : ''} gap-12 mb-12`}>
            
            {/* Left Column: Description & Services */}
            <div>
              <div className="mb-8">
                <div className="w-12 h-1 bg-dynasty-lime mb-6"></div>
                <div className="text-gray-300 text-lg leading-relaxed font-light">
                  {data.description}
                </div>
              </div>

              <div>
                <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                  <Target className="w-5 h-5 text-dynasty-blue" /> Services Provided
                </h3>
                <ul className="space-y-3 text-gray-400 text-sm">
                  {data.services.map((service, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="w-1.5 h-1.5 bg-dynasty-lime rounded-full mt-1.5 shrink-0"></span>
                      {service}
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Right Column: Chart (Only if data exists) */}
            {data.chart && (
              <div className="bg-white/5 rounded-xl p-6 border border-white/10 relative overflow-hidden flex flex-col justify-center pl-32">
                {/* Chart Background Gradient */}
                <div className="absolute inset-0 bg-gradient-to-t from-dynasty-blue/20 to-transparent pointer-events-none"></div>
                
                {/* Custom SVG Chart */}
                <div className="relative w-full aspect-[4/3] pt-4">
                  {/* Y-Axis Title */}
                  <div className="absolute -left-28 top-1/2 -translate-y-1/2 -rotate-90 text-[10px] text-dynasty-blue font-bold font-mono tracking-widest whitespace-nowrap">
                    {data.chart.yLabel}
                  </div>

                  {/* Y-Axis Lines */}
                  {data.chart.yValues.map((val, i) => (
                    <div key={i} className="absolute w-full border-t border-white/5 flex items-center text-[10px] text-gray-500" style={{ top: `${i * 20}%` }}>
                        <span className="absolute -left-10 font-mono text-xs">
                            {typeof val === 'number' ? (val === 0 ? '0' : `$${val}M`) : val}
                        </span>
                    </div>
                  ))}
                  
                  <svg className="w-full h-full overflow-visible" viewBox="0 0 300 200" preserveAspectRatio="none">
                    <defs>
                      <linearGradient id={`chartGradient-${projectId}`} x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor={data.chart.gradientColor} stopOpacity="0.5"/>
                        <stop offset="100%" stopColor={data.chart.gradientColor} stopOpacity="0"/>
                      </linearGradient>
                    </defs>
                    
                    {/* Area under curve */}
                    <path 
                      d={data.chart.pathFill}
                      fill={`url(#chartGradient-${projectId})`} 
                      className="opacity-30"
                    />
                    
                    {/* The Line */}
                    <path 
                      d={data.chart.pathLine}
                      fill="none" 
                      stroke={data.chart.lineColor}
                      strokeWidth="3" 
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="drop-shadow-[0_0_10px_rgba(245,158,11,0.5)]"
                    />
                    
                    {/* Peak Point (ATH) */}
                    <g className="animate-[pulse_3s_ease-in-out_infinite]">
                      <circle cx={data.chart.peakConfig.cx} cy={data.chart.peakConfig.cy} r="6" fill={data.chart.lineColor} />
                      <circle cx={data.chart.peakConfig.cx} cy={data.chart.peakConfig.cy} r="12" fill={data.chart.lineColor} fillOpacity="0.3" />
                      <text 
                          x={parseInt(data.chart.peakConfig.cx) - 10} 
                          y={parseInt(data.chart.peakConfig.cy) - 10} 
                          fill={data.chart.lineColor} 
                          fontSize="12" 
                          fontWeight="bold" 
                          textAnchor="end" 
                          fontFamily="sans-serif"
                      >
                          {data.chart.athLabel}
                      </text>
                    </g>
                  </svg>

                  {/* X-Axis Labels */}
                  <div className="flex justify-between text-[10px] text-gray-400 mt-2 font-mono uppercase tracking-wider">
                    <span>Launch</span>
                    <span>Week 1</span>
                    <span>Week 2</span>
                    <span>Week 3</span>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Bottom Section: Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {data.stats.map((stat, i) => (
               <div key={i} className="bg-dynasty-blue/10 border border-dynasty-blue/20 p-6 rounded-xl text-center group hover:bg-dynasty-blue/20 transition-colors">
                <div className="flex justify-center mb-4">
                  {stat.icon}
                </div>
                <h4 className="text-4xl md:text-5xl font-bold text-white mb-2">{stat.value}</h4>
                <p className="text-dynasty-blue font-bold uppercase tracking-wider text-sm mb-2">{stat.label}</p>
                <p className="text-gray-400 text-xs">{stat.sub}</p>
              </div>
            ))}

          </div>

          {/* Disclaimer */}
          <div className="mt-12 pt-6 border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-4 text-[10px] text-gray-600">
             <p className="text-center md:text-left">
               Disclaimer: Past results do not guarantee future results. Market conditions, narratives, product market fit along with other factors cause varying results.
             </p>
             <div className="font-sans font-bold tracking-tighter text-gray-500">
                DY<span className="text-dynasty-blue">N</span>ASTY
             </div>
          </div>
        </div>

      </div>
    </div>
  );
};

export default CaseStudyModal;